Repository mjurkowski/WDP-1906-03, pull requests merged in 2019-07, with the labels that each got.

#5 Task 37
  src/partials/50_section-products.html
  src/sass/components/_button.scss
  src/sass/components/_product-box.scss
Labels: Ready to merge

#13 Task 56
  src/images/bargain-main-1.jpg
  src/images/bargain-main-2.jpg
  src/images/bargain-main-3.jpg
  src/index.html
  src/partials/40_section-bargain.html
  src/sass/components/_section--bargain.scss
  src/sass/style.scss
Labels: Ready for review

#4 Task 35
  src/partials/30_section-features.html
  src/partials/50_section-products.html
  src/sass/components/_button.scss
  src/sass/components/_feature-box.scss
  src/sass/components/_product-box.scss
Labels: Ready to merge

#10 Task 38
  src/partials/10_header.html
  src/sass/components/_footer.scss
  src/sass/components/_panel-bar.scss
  src/sass/components/_product-box.scss
Labels: Ready to merge

#6 Task 40
  src/partials/50_section-products.html
  src/partials/70_section-blog-posts.html
  src/sass/components/_button.scss
  src/sass/components/_post-box.scss
Labels: Ready to merge

#14 Task 57
  src/partials/40_section-bargain.html
Labels: Ready for review

#16 Fix footer bugs
  src/sass/components/_footer.scss
Labels: Ready for review

#15 task-36-38
  src/partials/50_section-products.html
  src/sass/components/_product-box.scss
Labels: Ready to merge

#8 Task 42
  src/partials/10_header.html
  src/sass/components/_header.scss
Labels: Ready to merge

#12 Task 44
  src/partials/10_header.html
  src/sass/components/_header.scss
Labels: Ready to merge

#11 Task 43
  src/index.html
  src/partials/10_header.html
  src/sass/components/_button.scss
  src/sass/components/_header.scss
  src/sass/components/_panel-bar.scss
  src/scripts/togglemenu.js
Labels: Ready to merge

#19 Task 68
  src/partials/70_section-blog-posts.html
  src/sass/components/_post-box.scss
Labels: Ready to merge

#18 Task 47
  src/partials/70_section-blog-posts.html
  src/sass/components/_post-box.scss
Labels: Ready for review

#23 Task 66
  src/partials/70_section-blog-posts.html
Labels: Ready to merge

#25 Task 53
  .eslintignore
  src/index.html
  src/partials/20_section-promoted.html
  src/sass/_variables.scss
  src/sass/components/_promo-box.scss
  src/sass/style.scss
  src/scripts/Tocca.min.js
  src/scripts/carpousel.js
Labels: Ready to merge

#22 Task 49
  src/images/product-chair-1.jpeg
  src/images/product-chair-2.jpeg
  src/images/product-chair-3.jpeg
  src/images/product-chair-4.jpeg
  src/images/product-chair-5.jpeg
  src/images/product-chair-6.jpeg
  src/images/product-chair-7.jpeg
  src/images/product-chair-8.jpeg
  src/images/product-dining-1.jpeg
  src/images/product-dining-2.jpeg
  src/images/product-dining-3.jpeg
  src/images/product-dining-4.jpeg
  src/images/product-dining-5.jpeg
  src/images/product-dining-6.jpeg
  src/images/product-dining-7.jpeg
  src/images/product-dining-8.jpeg
  src/images/product-sofa-1.jpeg
  src/images/product-sofa-2.jpeg
  src/images/product-sofa-3.jpeg
  src/images/product-sofa-4.jpeg
  src/images/product-sofa-5.jpeg
  src/images/product-sofa-6.jpeg
  src/images/product-sofa-7.jpeg
  src/images/product-sofa-8.jpeg
  src/images/product-table-1.jpeg
  src/images/product-table-2.jpeg
  src/images/product-table-3.jpeg
  src/images/product-table-4.jpeg
  src/images/product-table-5.jpeg
  src/images/product-table-6.jpeg
  src/images/product-table-7.jpeg
  src/images/product-table-8.jpeg
  src/partials/50_section-products.html
  src/sass/components/_panel-bar.scss
  src/sass/components/_product-box.scss
Labels: Conflicts to resolve, Ready to merge

#26 Task 55
  src/partials/20_section-promoted.html
  src/sass/components/_promo-box.scss
Labels: Ready to merge

#21 Task 51
  src/index.html
  src/partials/50_section-products.html
  src/sass/components/_product-box.scss
  src/scripts/star-ranking.js
Labels: Ready for review
